#!/bin/sh
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AAAfEPTki7DAzJoB3uAFWRh9a/subset0.zip?dl=0' -O subset0.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AABJt-eyNWIKcfrWowoeTfzGa/subset1.zip?dl=0' -O subset1.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AAA8PYZxcd7H24SWCN2zSuR6a/subset2.zip?dl=0' -O subset2.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AAB70iYQN8yvTslbbo4-I72pa/subset3.zip?dl=0' -O subset3.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AABacOTGyiBGXrM012BJZnZLa/subset4.zip?dl=0' -O subset4.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AAAs2wbJxbNM44-uafZyoMVca/subset5.zip?dl=0' -O subset5.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AADuHVxx7RN5Le1n1it_aotka/subset6.zip?dl=0' -O subset6.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AADsRcbeiDjbJsJ3McD3zYt9a/subset7.zip?dl=0' -O subset7.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AADE1Z6JUeAQ5Ua6fwETH8yEa/subset8.zip?dl=0' -O subset8.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AADg2YpNOjYrlqxM_DgqB7T3a/subset9.zip?dl=0' -O subset9.zip
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AAANW5Vmi5IClbfh9bboGWwwa/annotations.csv?dl=0' -O annotations.csv
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AACEWJdqnR-tB9aWFlh_Iuula/candidates.csv?dl=0' -O candidates.csv
sudo wget -c 'https://www.dropbox.com/sh/mtip9dx6zt9nb3z/AAA8cDP9FK7fJJ_RY_DCSyYua/sampleSubmission.csv?dl=0' -O sampleSubmission.csv
sudo 7z x subset0.zip
sudo rm subset0.zip
sudo 7z x subset1.zip
sudo rm subset1.zip
sudo 7z x subset2.zip
sudo rm subset2.zip
sudo 7z x subset3.zip
sudo rm subset3.zip
sudo 7z x subset4.zip
sudo rm subset4.zip
sudo 7z x subset5.zip
sudo rm subset5.zip
sudo 7z x subset6.zip
sudo rm subset6.zip
sudo 7z x subset7.zip
sudo rm subset7.zip
sudo 7z x subset8.zip
sudo rm subset8.zip
sudo 7z x subset9.zip
sudo rm subset9.zip
